language: java
jdk:
  - oraclejdk6
env: DISPLAY=:99.0
env: GRADLE_OPTS="-XX:MaxPermSize=250m -Xmx768m"
script: ./gradle jar
after_script:
  - test -f ./build/libs/gradle-jxr-plugin.jar
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: /bin/true